import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  
  tutorialSidebar: [
    'intro',
    'supported-chains',
    {
      type: 'category',
      label: 'Solide IDE',
      collapsible: true,
      items: [
        "solide-ide/load-contract-source",
        "solide-ide/load-github-source",
        "solide-ide/aspect-ide",
      ],
    },
    {
      type: 'category',
      label: 'Socials',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'link',
          label: 'X',
          href: 'https://twitter.com/SolideProject',
        },
        {
          type: 'link',
          label: 'Github',
          href: 'https://github.com/solide-project',
        },
      ],
    },
  ],

};

export default sidebars;
