import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: '👋 Introduction',
    },
    {
      type: 'doc',
      id: 'supported-chains',
      label: '⛓️ Support Chains',
    },
    {
      type: 'category',
      label: '💡 Solide IDEs',
      collapsible: false,
      items: [
        {
          type: 'category',
          label: '🟣 Solide',
          items: [
            {
              type: 'doc',
              id: 'ide/sol-ide-contract',
              label: 'Import Contract Address',
            },
            {
              type: 'doc',
              id: 'ide/sol-ide-github',
              label: 'Import Github Repository',
            },
          ]
        },
        {
          type: 'doc',
          id: 'ide/stylus-ide',
          label: '🔵 Stylide',
        },
        {
          type: 'doc',
          id: 'ide/aspect-ide',
          label: '🔵 Aspectide (Comming Soon)',
        },
        {
          type: 'doc',
          id: 'ide/move-ide',
          label: '🟡 Movide (Comming Soon)',
        },
      ],
    },
    {
      type: 'category',
      label: '⚙️ Tools',
      collapsible: true,
      items: [
        {
          type: 'doc',
          id: 'tools/web3-contract-plugin',
          label: '🔌 Web3 Plugin Contracts',
        },
        {
          type: 'doc',
          id: 'tools/solidity-database',
          label: '🧭 Solidity Database',
        },
        {
          type: 'doc',
          id: 'tools/awesome-solidity-learn',
          label: '👓 Awesome Solidity Learn (New!)',
        },
      ],
    },
    {
      type: 'category',
      label: 'Socials',
      collapsible: false,
      collapsed: false,
      items: [
        {
          type: 'link',
          label: '⭐ X (Twitter)',
          href: 'https://x.com/SolideProject',
        },
        {
          type: 'link',
          label: '⭐ Github',
          href: 'https://github.com/solide-project',
        },
      ],
    },
  ],

};

export default sidebars;
